import type { V2ServicePageProps } from "./V2ServicePage";
import React from "react";

export const aeoGeoContent: V2ServicePageProps = {
  hero: {
    badge: "AEO & GEO · AI search visibility",
    title: React.createElement(React.Fragment, null,
      "Get cited by ChatGPT, Perplexity,",
      React.createElement("br"),
      "and ", React.createElement("em", null, "Google AI Overviews."),
    ),
    lead: "Renters are no longer just typing into Google. They are asking AI assistants conversational questions like \"best climate-controlled storage near me\" or \"cheapest 10x10 units in [city].\" If your facility is not optimised for these answer engines, you are losing move-ins to whichever competitor the AI recommends instead.",
    primaryCta: { label: "Get your free AEO + GEO visibility audit", href: "/contact" },
    ghostCta: { label: "See AI citation data →", href: "#proof" },
    dashboard: {
      title: "AI citation tracker — Live",
      tracking: "Monitoring",
      period: "Last 30 days",
      metrics: [
        { label: "AI mentions", value: "47", delta: "↑ from 0 baseline" },
        { label: "Cited in AI Overviews", value: "12", delta: "Across key queries" },
        { label: "Entity confidence", value: "92%", delta: "Was 18% at start" },
      ],
      chartLabel: "AI citation frequency — trailing 14 weeks",
      sparkline: [4, 6, 9, 13, 18, 23, 28, 33, 38, 44, 50, 57, 64, 72],
      rankingsHeader: { pos: "Engine", kw: "Query", change: "Cited", clicks: "Last seen" },
      rankings: [
        { pos: "GPT", kw: "best climate storage [city]", change: "✓ Yes", clicks: "Today", top: true },
        { pos: "PPLX", kw: "10x10 storage near [zip]", change: "✓ Yes", clicks: "2d ago", top: true },
        { pos: "AIO", kw: "drive-up storage in [area]", change: "New", clicks: "5d ago", isNew: true },
        { pos: "GPT", kw: "RV storage [neighbourhood]", change: "✓ Yes", clicks: "1w ago" },
      ],
    },
  },
  marquee: ["Answer Engine Optimisation", "Generative Engine Optimisation", "ChatGPT visibility", "Perplexity citations", "Google AI Overviews", "Entity authority", "Storage-specific schema", "Answer-first content", "Knowledge graph wiring", "Citation consistency", "Multi-engine monitoring", "Zero-click recovery"],
  problem: {
    pill: "Why AI is rewriting search",
    headline: React.createElement(React.Fragment, null,
      "Renters are asking AI for",
      React.createElement("br"),
      "storage recommendations. Are you in the answer?",
    ),
    lead: "Most independent operators have never checked whether AI tools mention their facility. Most do not. National chains with strong entity authority are dominating AI-generated recommendations — and the operators losing those zero-click conversations rarely even know it is happening.",
    cards: [
      { num: "Problem 01", title: "Missing from AI answers entirely", desc: "When someone asks \"is climate-controlled storage worth it near my home?\", your facility is never mentioned. AI engines have no structured signal that you exist as a relevant entity for that query.", tag: "Entity authority · Citations" },
      { num: "Problem 02", title: "Outranked by national chains", desc: "Big brands with strong entity authority, structured schema, and consistent citations dominate AI-generated recommendations. Their storage facility surfaces; yours does not, even when you are physically closer.", tag: "Schema depth · NAP consistency" },
      { num: "Problem 03", title: "Lost zero-click opportunities", desc: "Many renters get full answers — including facility recommendations — without ever clicking through to a website or map. If you are not cited in the answer, the search ends before you ever had a chance.", tag: "Zero-click · AI Overviews" },
    ],
    visual: {
      title: "What AI invisibility costs",
      sub: "Audit of typical independent operator",
      rows: [
        { label: "AI tools citing the facility at audit start", value: "0 of 4", tone: "r", valueClass: "red" },
        { label: "Storage-specific schema types missing", value: "9 of 12", tone: "a", valueClass: "red" },
        { label: "NAP inconsistencies across the web", value: "14+", tone: "a", valueClass: "red" },
        { label: "After programme: cited across all 4 engines", value: "✓", tone: "g", valueClass: "green" },
      ],
      totalLabel: "Entity confidence score at month 3",
      totalValue: "92 / 100",
    },
    inlineCta: {
      strong: "Check whether AI tools recommend you today",
      body: "Free audit. We run your facility through ChatGPT, Perplexity, Gemini, and Google AI Overviews and show you exactly where you are missing.",
      ctaLabel: "Get free audit →",
      ctaHref: "/contact",
    },
  },
  approach: {
    pill: "Our AEO + GEO approach",
    headline: React.createElement(React.Fragment, null,
      "Build entity authority. Structure",
      React.createElement("br"),
      "for answer engines. Compound it.",
    ),
    lead: "We do not do generic AI optimisation. Every tactic is built specifically for storage operators and focused on one outcome — more qualified move-ins from both Google and AI-powered search.",
    steps: [
      { phase: "Step 01", title: "Entity authority & citation consistency", desc: "We strengthen your business as a recognisable entity across the web with consistent NAP, high-quality citations, and storage-specific schema markup so AI tools confidently recommend your facility instead of guessing.", tags: ["NAP", "Citations", "sameAs"] },
      { phase: "Step 02", title: "Answer-first content creation", desc: 'Hyper-targeted content that directly answers the questions real renters ask AI — "What size storage unit do I need?", "Is drive-up access worth it?", "Climate-controlled vs non-climate" — optimised for featured snippets and generative answers.', tags: ["Answer content", "Snippets", "FAQ schema"] },
      { phase: "Step 03", title: "Structured data & schema mastery", desc: "Advanced schema implementation — unit-type, pricing, availability signals, review markup, FAQ, LocalBusiness, SelfStorage — that helps AI engines understand and trust your data more than competitors.", tags: ["Schema", "JSON-LD", "Validation"] },
      { phase: "Step 04", title: "GBP + local signal reinforcement", desc: "Your GBP is optimised for both traditional map pack and AI Overviews via fresh photos, posts, reviews, and accurate attributes (gate hours, climate, vehicle/RV storage). Local signals double as AI training data.", tags: ["GBP", "Photos", "Attributes"] },
    ],
    ctaText: React.createElement(React.Fragment, null,
      React.createElement("strong", null, "Want to see where AI mentions your facility today?"),
      " Free written audit across ChatGPT, Perplexity, Gemini, and AI Overviews.",
    ),
    ctaLabel: "Start with a free audit →",
    ctaHref: "/contact",
  },
  proof: {
    pill: "Verified results",
    headline: "AI citation data from active client accounts.",
    dataCard: {
      title: "Single facility, TX — AEO/GEO rollout",
      source: "Multi-engine tracker",
      kpis: [
        { label: "Organic move-ins", value: "+148%", delta: "Including AI traffic" },
        { label: "AI citations", value: "47", delta: "Across 4 engines" },
        { label: "AI Overview presence", value: "12", delta: "Storage queries" },
      ],
      positionLabel: "Citation frequency by engine",
      positions: [
        { kw: "ChatGPT", w: "92%", num: "✓", top: true },
        { kw: "Perplexity", w: "88%", num: "✓", top: true },
        { kw: "Google AI Overviews", w: "78%", num: "✓" },
        { kw: "Gemini", w: "72%", num: "✓" },
        { kw: "Copilot", w: "58%", num: "✓" },
      ],
      journeyLabel: "Cumulative AI mentions — month by month",
      bars: [
        { h: 8, cls: "" }, { h: 14, cls: "" }, { h: 22, cls: "" },
        { h: 32, cls: "mid" }, { h: 44, cls: "mid" },
        { h: 56, cls: "high" }, { h: 68, cls: "high" }, { h: 80, cls: "high" },
        { h: 94, cls: "peak" },
      ],
      months: ["M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9"],
    },
    aggCards: [
      { num: React.createElement(React.Fragment, null, "+148", React.createElement("span", null, "%")), label: "Organic move-in lift", note: "Including AI-driven traffic" },
      { num: "4 / 4", label: "Major AI engines citing client", note: "By month four on average" },
      { num: React.createElement(React.Fragment, null, "92", React.createElement("span", null, "%")), label: "Avg. entity confidence score", note: "Was 18% at start" },
      { num: "$0", label: "Reliance on paid aggregator leads", note: "Several clients post-rollout" },
    ],
    testimonial: {
      quote: "We started seeing our facility recommended in ChatGPT answers around month three. By month six, our zero-click visibility was higher than two of the regional chains in our city — operators ten times our size who never even noticed AI was a channel.",
      attribution: "Multi-location operator",
      location: "Texas",
    },
    auditCta: {
      label: "Check your AI visibility today",
      text: "We run your facility through ChatGPT, Perplexity, Gemini, and Google AI Overviews against your top storage queries and deliver a written report showing exactly which engines recommend you and which do not.",
      features: [
        "Citation check across 4 major AI engines",
        "Storage-specific schema audit",
        "NAP and entity consistency review",
        "No sales call required to receive the audit",
      ],
      ctaLabel: "Request your free audit →",
      ctaHref: "/contact",
    },
  },
  faq: {
    pill: "Common questions",
    headline: "Things owners usually ask.",
    lead: "If your question is not here, reach out directly. We answer before you commit to anything.",
    asideStrong: "Is AEO actually worth it for storage?",
    asideBody: "We will run a free citation check across ChatGPT, Perplexity, Gemini, and Google AI Overviews against your top queries and tell you honestly whether AEO is your biggest lever right now or whether traditional SEO would move the needle faster.",
    asideCtaLabel: "Request a free conversation →",
    asideCtaHref: "/contact",
    items: [
      { q: "What exactly are AEO and GEO, and why should a storage owner care?", a: "AEO (Answer Engine Optimisation) and GEO (Generative Engine Optimisation) focus on getting your facility recommended directly in AI-powered answers from ChatGPT, Perplexity, Gemini, and Google AI Overviews. More renters now ask conversational questions like \"best climate-controlled storage near me\" — and if your facility is not surfaced, the AI recommends a competitor instead.", open: true },
      { q: "How is this different from regular Local SEO or GBP optimisation?", a: "Regular Local SEO helps you rank in the Google map pack and organic results. AEO and GEO go further by optimising your content, schema, entity strength, and citations so AI engines understand, trust, and actively recommend your facility in their generated responses. We combine both — strong traditional Local SEO plus the AEO/GEO layer." },
      { q: "How long does it take to see results?", a: "Initial improvements in traditional rankings and content performance appear within 30–60 days. Meaningful visibility in AI-generated answers typically appears between 60–120 days as AI models need consistent, authoritative signals over time. Most clients see compounding results after 90 days." },
      { q: "Do I need to rebuild my entire website?", a: "No. While a fast, well-structured site helps, you do not necessarily need a rebuild. We work with your existing site — WordPress, custom CMS, storEDGE, SiteLink — and focus on strategic improvements: proper schema, targeted answer content, optimised location pages, and stronger entity authority." },
      { q: "Will optimising for AEO/GEO affect my Google Maps ranking?", a: "Yes, positively. The strategies we use for AEO and GEO — structured data, high-quality content, review signals, citation consistency, entity building — are the same foundational elements that improve traditional GBP and map pack rankings. The signals reinforce each other." },
      { q: "Is AEO/GEO a temporary trend or here to stay?", a: "Here to stay. AI-powered search is rapidly growing and changing how people discover local businesses. Google is increasingly showing AI Overviews, and tools like ChatGPT and Perplexity are becoming primary search interfaces for many users. Facilities that optimise early will have a significant advantage." },
    ],
  },
  finalCta: {
    headline: React.createElement(React.Fragment, null,
      "Ready to rank in Google Maps",
      React.createElement("br"),
      "and AI answers? Free audit.",
    ),
    lead: "Get a free audit showing your current visibility on traditional search and emerging AI engines. We identify exactly why you are missing opportunities and how to fix it.",
    primaryLabel: "Claim my AEO + GEO audit",
    primaryHref: "/contact",
    ghostLabel: "See AI citation data first",
    reassurance: ["Citation check across 4 AI engines", "Schema and entity audit", "NAP consistency review", "Yours to keep regardless"],
  },
};
