import type { V2ServicePageProps } from "./V2ServicePage";
import React from "react";

export const backlinksContent: V2ServicePageProps = {
  hero: {
    badge: "Backlinks · Hyper-local authority",
    title: React.createElement(React.Fragment, null,
      "Backlinks earned in the communities",
      React.createElement("br"),
      "your ", React.createElement("em", null, "future renters already trust."),
    ),
    lead: "Quality backlinks act like trusted votes of confidence that tell Google and AI engines your facility is a legitimate, authoritative local business. We earn hyper-local backlinks from real community sources — moving companies, real estate groups, neighbourhood forums — not link farms.",
    primaryCta: { label: "Get your free backlink & authority audit", href: "/contact" },
    ghostCta: { label: "See authority growth →", href: "#proof" },
    dashboard: {
      title: "Authority tracker — Live",
      tracking: "Outreaching",
      period: "Last 90 days",
      metrics: [
        { label: "New referring domains", value: "23", delta: "↑ from 0 baseline" },
        { label: "Domain rating", value: "34", delta: "Was 12 at start" },
        { label: "Impressions", value: "+184%", delta: "vs prior 90 days" },
      ],
      chartLabel: "Referring domains — trailing 14 weeks",
      sparkline: [4, 6, 8, 10, 12, 14, 17, 19, 22, 24, 27, 30, 33, 36],
      rankingsHeader: { pos: "DR", kw: "Source", change: "Type", clicks: "Placed" },
      rankings: [
        { pos: "68", kw: "BiggerPockets · local thread", change: "Forum", clicks: "M2", top: true },
        { pos: "52", kw: "r/[citymoms] · storage recs", change: "Reddit", clicks: "M2", top: true },
        { pos: "44", kw: "Local realtor blog network", change: "Partner", clicks: "M3", isNew: true },
        { pos: "38", kw: "Apartment complex resource page", change: "Partner", clicks: "M3" },
      ],
    },
  },
  marquee: ["Hyper-local backlinks", "No black-hat tactics", "Storage-specific publications", "Community-sourced placements", "Built for AEO & GEO", "Transparent reporting", "Local partner outreach", "Real estate forum mentions", "Digital PR", "Citation cleanup", "Disavow audit", "Earned, not paid"],
  problem: {
    pill: "Why you are stuck on page two",
    headline: React.createElement(React.Fragment, null,
      "Without authority, even great GBPs",
      React.createElement("br"),
      "stay below national chains.",
    ),
    lead: "Even with a great Google Business Profile and an optimised website, many independent operators stay stuck on page two because they lack the authority signals that come from real backlinks.",
    cards: [
      { num: "Problem 01", title: "Invisible to Google's authority signals", desc: "Your site has very few external links pointing to it, so Google does not see you as an authoritative local business worth ranking above your competition. Authority is the missing ingredient.", tag: "Domain rating · Authority" },
      { num: "Problem 02", title: "Outranked by national chains", desc: "Larger storage brands have hundreds of strong backlinks pointing at them. Without your own, breaking into the top three of the map pack is extremely difficult — especially in mid- and large-metro markets.", tag: "Competitor authority gap" },
      { num: "Problem 03", title: "Risky or wasted links from prior agencies", desc: "Many owners end up with spammy or irrelevant backlinks from past agencies or shortcuts. The wrong links can actually hurt your rankings instead of helping them, and the cleanup matters as much as the new outreach.", tag: "Toxic links · Disavow · Cleanup" },
    ],
    visual: {
      title: "What missing authority is costing you",
      sub: "Typical independent operator audit",
      rows: [
        { label: "Avg. local-community backlinks at audit start", value: "0", tone: "r", valueClass: "red" },
        { label: "Toxic links flagged for disavow", value: "8–14", tone: "a", valueClass: "red" },
        { label: "Domain rating gap vs national chain", value: "−42 pts", tone: "a", valueClass: "red" },
        { label: "After 90 days: new referring domains earned", value: "18–30", tone: "g", valueClass: "green" },
      ],
      totalLabel: "Avg. domain rating increase by month 3",
      totalValue: "+22 pts",
    },
    inlineCta: {
      strong: "See exactly which links are helping or hurting your site",
      body: "Free audit. We map your existing profile, flag toxic links, and identify local communities where you should be earning new ones.",
      ctaLabel: "Get free audit →",
      ctaHref: "/contact",
    },
  },
  approach: {
    pill: "Our backlink strategy",
    headline: React.createElement(React.Fragment, null,
      "Hyper-local, editorially earned,",
      React.createElement("br"),
      "and built for the long run.",
    ),
    lead: "We do not do generic link building. Every backlink we pursue is relevant to the self-storage industry and tied to your specific local market. These are the four community channels we work in parallel for every client.",
    steps: [
      { phase: "Week 01", title: "Audit, score, and disavow", desc: "We map every existing link pointing at your site, score them for quality and relevance, and flag toxic ones for cleanup. Cleanup runs in parallel with new outreach — sometimes the disavow alone delivers ranking lift.", tags: ["Backlink audit", "Disavow", "Cleanup"] },
      { phase: "Step 02", title: "Local partnership outreach", desc: "Moving companies, real estate agents, apartment complexes, and chambers of commerce — partners who naturally refer storage customers. Most are happy to link to a trusted local operator once we make the introduction.", tags: ["Movers", "Realtors", "Apartments", "Chambers"] },
      { phase: "Step 03", title: "Community-source placements", desc: "City moms groups, neighbourhood subreddits, BiggerPockets and real estate investor forums, local Facebook groups. Recommendations earned in context — the most powerful kind of backlink for both Google and AI engines.", tags: ["Subreddits", "FB groups", "BiggerPockets"] },
      { phase: "Step 04", title: "Digital PR and brand mentions", desc: "We create link-worthy content — moving guides, comparisons, neighbourhood storage checklists — that naturally attract editorial links and brand mentions from local news and lifestyle publications.", tags: ["Editorial links", "Brand mentions", "Local PR"] },
    ],
    ctaText: React.createElement(React.Fragment, null,
      React.createElement("strong", null, "Want to see your current authority profile?"),
      " Free audit covering toxic links, opportunity gaps, and community-source targets.",
    ),
    ctaLabel: "Start with a free audit →",
    ctaHref: "/contact",
  },
  proof: {
    pill: "Verified results",
    headline: "Authority growth from real client engagements.",
    dataCard: {
      title: "Single facility, AZ — 90-day backlink programme",
      source: "GSC · Ahrefs",
      kpis: [
        { label: "New referring domains", value: "23", delta: "All editorially earned" },
        { label: "Impressions", value: "+184%", delta: "vs prior 90 days" },
        { label: "Avg. position lift", value: "+6.4", delta: "Across primary keywords" },
      ],
      positionLabel: "Backlink mix by source type",
      positions: [
        { kw: "Local partner placements", w: "94%", num: "9", top: true },
        { kw: "Community / forum mentions", w: "82%", num: "7", top: true },
        { kw: "Editorial / digital PR", w: "68%", num: "4" },
        { kw: "Industry / trade publications", w: "55%", num: "3" },
        { kw: "Toxic links disavowed", w: "100%", num: "12" },
      ],
      journeyLabel: "Cumulative referring domains — month by month",
      bars: [
        { h: 10, cls: "" }, { h: 18, cls: "" }, { h: 26, cls: "" },
        { h: 36, cls: "mid" }, { h: 46, cls: "mid" },
        { h: 58, cls: "high" }, { h: 70, cls: "high" }, { h: 82, cls: "high" },
        { h: 94, cls: "peak" },
      ],
      months: ["M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9"],
    },
    aggCards: [
      { num: React.createElement(React.Fragment, null, "23", React.createElement("span", null, " avg.")), label: "New referring domains per facility", note: "Within first 90 days" },
      { num: React.createElement(React.Fragment, null, "+22", React.createElement("span", null, " pts")), label: "Avg. domain rating increase", note: "By month three" },
      { num: "0", label: "Black-hat tactics or paid links", note: "Every placement editorially earned" },
      { num: React.createElement(React.Fragment, null, "94", React.createElement("span", null, "%")), label: "Placements still live at year two", note: "Real sites, permanent links" },
    ],
    testimonial: {
      quote: "Other agencies sent me lists of links from sites I had never heard of. SelfStorage.help built relationships with actual local movers and apartment communities in my city. Within three months I started seeing my facility recommended in local Facebook groups without me asking.",
      attribution: "Diana Morales — Single-Facility Operator",
      location: "Arizona",
    },
    auditCta: {
      label: "Run the authority audit on your site",
      text: "We pull your full backlink profile, flag the toxic links dragging you down, and identify the local communities where you should be earning links instead.",
      features: [
        "Full backlink profile audit",
        "Toxic link flagging and disavow plan",
        "Local community opportunity map",
        "No sales call required to receive the audit",
      ],
      ctaLabel: "Request your free audit →",
      ctaHref: "/contact",
    },
  },
  faq: {
    pill: "Common questions",
    headline: "Things owners usually ask.",
    lead: "If your question is not here, reach out directly. We answer before you commit to anything.",
    asideStrong: "Worried about Google penalties?",
    asideBody: "Every link we build is editorially earned from a relevant, real source. No PBNs, no link farms, no paid placements that violate Google's guidelines. We will walk you through the exact process before any outreach starts.",
    asideCtaLabel: "Request a free conversation →",
    asideCtaHref: "/contact",
    items: [
      { q: "Are these backlinks safe? I have heard horror stories.", a: "Every link we build is editorially earned from a relevant, real source. We do not use private blog networks, link farms, or paid placements that violate Google's guidelines. The horror stories you have heard come from agencies that take shortcuts. Our process is the opposite, which is also why it takes 90 days rather than one.", open: true },
      { q: "How many backlinks will I get?", a: "In a typical 90-day engagement we build between 18 and 30 high-quality backlinks from sources directly relevant to your service area. Volume varies based on your market and what is available in your specific local community. Quality is always the priority over raw count." },
      { q: "Will this help with AI search like ChatGPT and Perplexity?", a: "Yes. AI engines weigh entity authority heavily, which is built through brand mentions and links across trusted sources. Our community-sourced approach builds exactly the kind of citation pattern AI engines look for when answering local storage queries." },
      { q: "What if I already have backlinks from a previous agency?", a: "The first thing we do is audit your existing backlink profile. If you have toxic or low-quality links, we either pursue removal or disavow them through Google Search Console. Cleanup is part of the engagement and often delivers ranking lift before any new links are built." },
      { q: "Can I see the actual links you build?", a: "Every link we earn is reported in your monthly summary with the source, the page it sits on, the anchor text, and a quality score. Total transparency. You can verify each one yourself in Google Search Console as it gets indexed." },
      { q: "Will my rankings drop if I stop the service?", a: "No. The backlinks we build are permanent placements on real sites and continue to provide authority signals long after the engagement ends. Some operators stay on for ongoing momentum, others step down to a maintenance plan after the first six months once the foundation is set." },
    ],
  },
  finalCta: {
    headline: React.createElement(React.Fragment, null,
      "Find out what your current backlink",
      React.createElement("br"),
      "profile looks like. Free audit.",
    ),
    lead: "Drop your facility website and we will send a full backlink audit showing your current authority score, your toxic links, and the local communities where you should be earning links instead.",
    primaryLabel: "Send my authority audit",
    primaryHref: "/contact",
    ghostLabel: "See authority growth first",
    reassurance: ["Full backlink profile audit", "Toxic link disavow plan", "Community opportunity map", "Yours to keep regardless"],
  },
};
