import type { V2ServicePageProps } from "./V2ServicePage";
import React from "react";

export const contentStrategyContent: V2ServicePageProps = {
  hero: {
    badge: "Content Strategy & Writing · Hyper-local",
    title: React.createElement(React.Fragment, null,
      "Hyper-local content that puts",
      React.createElement("br"),
      "your facility in front of ",
      React.createElement("em", null, "nearby renters."),
    ),
    lead: "When someone within five miles of your facility searches for storage, the pages that mention their specific neighbourhood, nearby landmarks, and ZIP code win the click. Most operators publish generic content that could belong to any facility. We do the opposite — research-first, ZIP-coded copy that ranks where renters actually live.",
    primaryCta: { label: "Get a free content opportunity audit", href: "/contact" },
    ghostCta: { label: "See content performance →", href: "#proof" },
    dashboard: {
      title: "Content opportunity map — Live",
      tracking: "Researching",
      period: "Trade area",
      metrics: [
        { label: "ZIPs mapped", value: "14", delta: "Within 5-mile radius" },
        { label: "Keyword opportunities", value: "186", delta: "Low-difficulty wins" },
        { label: "Competitor gaps", value: "47", delta: "Pages no one ranks for" },
      ],
      chartLabel: "Page production — trailing 14 weeks",
      sparkline: [12, 18, 24, 30, 36, 44, 52, 60, 68, 74, 82, 88, 92, 96],
      rankingsHeader: { pos: "Pos.", kw: "Page / keyword", change: "Change", clicks: "Clicks" },
      rankings: [
        { pos: "#1", kw: "climate storage [neighbourhood]", change: "↑ +12", clicks: "418", top: true },
        { pos: "#2", kw: "10x10 storage [ZIP]", change: "↑ +7", clicks: "284", top: true },
        { pos: "#3", kw: "rv storage near [landmark]", change: "New", clicks: "192", isNew: true },
        { pos: "#5", kw: "business storage [city]", change: "↑ +4", clicks: "127" },
      ],
    },
  },
  marquee: ["Hyper-local content", "ZIP-level targeting", "GBP posts that rank", "Location landing pages", "SEMrush research", "Ahrefs competitor analysis", "Neighbourhood copy", "Unit-type pages", "Seasonal content", "AI-search ready", "Schema-rich", "Multi-location coverage"],
  problem: {
    pill: "Why generic content fails",
    headline: React.createElement(React.Fragment, null,
      "Storage content that could belong",
      React.createElement("br"),
      "to anyone, ranks for no one.",
    ),
    lead: "Most operators publish content that reads like every other facility in the country. Same unit size guide, same packing tips, same move-in checklist. Search engines have seen all of it before — and so have the renters you are trying to reach.",
    cards: [
      { num: "Problem 01", title: "Reads like every other facility", desc: "Your service pages talk about storage in general terms. There is no mention of your city, neighbourhoods, or service area. Google has no reason to prefer your page over a national chain's.", tag: "Generic copy · No local hooks" },
      { num: "Problem 02", title: "No ZIP-code level relevance", desc: "You serve renters across 10+ ZIP codes, but your content does not name any of them. The searcher in 30309 has no signal that you serve their exact area.", tag: "ZIP coverage · Neighbourhoods" },
      { num: "Problem 03", title: "Stale Google Business Profile content", desc: "Your GBP description was written once and never touched. No weekly posts, no neighbourhood references, no seasonal updates. Google reads inactivity as a relevance signal — a bad one.", tag: "GBP posts · Q&A · Photos" },
    ],
    visual: {
      title: "What the content gap actually costs",
      sub: "Typical single facility, monthly",
      rows: [
        { label: "ZIPs in service area without a page", value: "12 of 14", tone: "r", valueClass: "red" },
        { label: "Long-tail searches you do not rank for", value: "186+", tone: "a", valueClass: "red" },
        { label: "GBP posts published in last 90 days", value: "0", tone: "a", valueClass: "red" },
        { label: "After programme: full ZIP + GBP coverage", value: "100%", tone: "g", valueClass: "green" },
      ],
      totalLabel: "Page coverage of service area by month 4",
      totalValue: "14 / 14",
    },
    inlineCta: {
      strong: "See which content opportunities exist around your facility",
      body: "Free audit. We map every ZIP, every competitor gap, and the searches you should already be ranking for.",
      ctaLabel: "Get free audit →",
      ctaHref: "/contact",
    },
  },
  approach: {
    pill: "Our content process",
    headline: React.createElement(React.Fragment, null,
      "Research first. Write second.",
      React.createElement("br"),
      "Measure every piece.",
    ),
    lead: "A real content programme is not a list of titles. It is a research-first process that maps opportunity, produces content that ranks, and tracks performance over time.",
    steps: [
      { phase: "Week 01", title: "Market and ZIP research", desc: "We map every ZIP in your service area, pull SEMrush and Ahrefs data on competitors and search opportunities, and analyse public data sources for local context. You receive a written content opportunity report.", tags: ["ZIP mapping", "SEMrush", "Ahrefs"] },
      { phase: "Week 02", title: "Content strategy and calendar", desc: "A 90-day content calendar covering both GBP and website. For single-facility operators it is built around your service radius. For multi-facility, a layered local + national plan.", tags: ["Calendar", "Local + national", "Topics"] },
      { phase: "Week 03+", title: "Hyper-local copy goes live", desc: "Highest-leverage pieces ship first — the location pages and GBP posts that target the highest-volume, lowest-competition opportunities in your market. Real neighbourhood and landmark references built in, not just city name swaps.", tags: ["Location pages", "Unit pages", "GBP posts"] },
      { phase: "Month 03+", title: "Measure and compound", desc: "Pieces that are performing get reinforced. Pieces that are not get reworked. As more pieces rank, overall site authority grows and older pieces start ranking for more queries. The programme is designed to keep compounding.", tags: ["Refreshes", "Performance", "Authority"] },
    ],
    ctaText: React.createElement(React.Fragment, null,
      React.createElement("strong", null, "Want the content opportunity report for your facility?"),
      " Free, written, and delivered in five business days.",
    ),
    ctaLabel: "Get the opportunity report →",
    ctaHref: "/contact",
  },
  proof: {
    pill: "Verified results",
    headline: "Content performance from real client portfolios.",
    dataCard: {
      title: "Five-facility portfolio, DFW — Months 1–9",
      source: "GSC · SEMrush",
      kpis: [
        { label: "Organic sessions", value: "4.2×", delta: "vs baseline" },
        { label: "Ranking pages", value: "284", delta: "Up from 31" },
        { label: "ZIPs with a ranking page", value: "62 / 70", delta: "Across portfolio" },
      ],
      positionLabel: "Ranking spread — by content type",
      positions: [
        { kw: "Neighbourhood location pages", w: "94%", num: "#1–3", top: true },
        { kw: "Unit-size pages by ZIP", w: "86%", num: "#1–5", top: true },
        { kw: "Use-case content (RV, business)", w: "78%", num: "#1–5" },
        { kw: "Seasonal / move-trend pieces", w: "65%", num: "#1–10" },
        { kw: "GBP post visibility", w: "82%", num: "Active" },
      ],
      journeyLabel: "Organic sessions — month by month",
      bars: [
        { h: 12, cls: "" }, { h: 18, cls: "" }, { h: 25, cls: "" },
        { h: 36, cls: "mid" }, { h: 48, cls: "mid" },
        { h: 60, cls: "high" }, { h: 72, cls: "high" }, { h: 84, cls: "high" },
        { h: 96, cls: "peak" },
      ],
      months: ["M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9"],
    },
    aggCards: [
      { num: "4.2×", label: "Avg. organic traffic at month 6", note: "vs engagement-start baseline" },
      { num: React.createElement(React.Fragment, null, "60", React.createElement("span", null, "+")), label: "ZIPs covered per multi-facility client", note: "Each with a ranking page" },
      { num: React.createElement(React.Fragment, null, "186", React.createElement("span", null, " kw")), label: "Avg. new long-tail rankings per facility", note: "Within first 6 months" },
      { num: "2–4", label: "Substantive pieces per month", note: "Plus weekly GBP posts" },
    ],
    testimonial: {
      quote: "We had five facilities and one blog. Every article was generic and nothing was ranking. SelfStorage.help mapped every ZIP in our coverage area and built content specifically for each one. Within six months our organic traffic was up four times and we were ranking for searches we did not even know existed.",
      attribution: "Aisha Patel — Operations Director",
      location: "Five-facility portfolio, Dallas-Fort Worth",
    },
    auditCta: {
      label: "Run the opportunity audit on your market",
      text: "We pull SEMrush and Ahrefs data on your competitors, map your service-area ZIPs, and deliver a written report showing exactly where you should be writing.",
      features: [
        "ZIP-by-ZIP opportunity map",
        "Competitor ranking gaps",
        "GBP content audit included",
        "No sales call required to receive the audit",
      ],
      ctaLabel: "Request your free audit →",
      ctaHref: "/contact",
    },
  },
  faq: {
    pill: "Common questions",
    headline: "Things owners usually ask.",
    lead: "If your question is not here, reach out directly. We answer before you commit to anything.",
    asideStrong: "Not sure if content is your bottleneck?",
    asideBody: "We will tell you honestly whether content is what will move your rankings, or whether technical work or local SEO would be the bigger lever for your specific facility.",
    asideCtaLabel: "Request a free conversation →",
    asideCtaHref: "/contact",
    items: [
      { q: "How is this different from a regular content writing service?", a: "Regular content services write articles. We run a research-first content programme tied to your specific local market. Every piece is informed by SEMrush, Ahrefs, and ZIP-level research. Writing is the last 30% of the work; research is the first 70%.", open: true },
      { q: "How many pieces will you produce per month?", a: "Typically two to four website pieces per month plus weekly GBP posts. Volume varies based on your service area size and competition. We prioritise quality and ranking impact over raw output." },
      { q: "Do you use AI to write the content?", a: "We use AI as a research and drafting aid, but every piece is researched, edited, and finalised by a human who understands storage. AI-only content does not rank reliably and does not represent your brand the way you would want." },
      { q: "How do you handle multi-facility operators differently?", a: "Multi-facility operators get a two-layer strategy. The local layer covers every ZIP within 10 miles of each facility with location-specific content. The national layer builds portfolio-wide authority through state, regional, and national content." },
      { q: "Will this help me show up in AI search results?", a: "Yes. AI engines rely on structured content, entity authority, and citation patterns to surface businesses in answers. Our hyper-local content with proper schema, real local references, and high topical authority is exactly what AI engines look for." },
      { q: "How long until I see ranking results?", a: "Most operators see initial ranking movement within 60 days of the first content going live. Full impact typically settles in by month four or five, with results continuing to compound from there. Content is the slowest SEO service to show results — and the most durable once it does." },
    ],
  },
  finalCta: {
    headline: React.createElement(React.Fragment, null,
      "Find the content opportunities",
      React.createElement("br"),
      "around your facility. Free audit.",
    ),
    lead: "Drop your facility website and we will send a content opportunity report covering the ZIPs you should target, the searches your competitors are ranking for, and the gaps where you can win quickly.",
    primaryLabel: "Send my opportunity audit",
    primaryHref: "/contact",
    ghostLabel: "See content performance first",
    reassurance: ["ZIP-by-ZIP opportunity map", "Competitor gap analysis", "GBP content included", "Yours to keep regardless"],
  },
};
