import type { V2ServicePageProps } from "./V2ServicePage";
import React from "react";

export const localSeoContent: V2ServicePageProps = {
  hero: {
    badge: "Local SEO & Google Business Profile",
    title: React.createElement(React.Fragment, null,
      "Rank #1–3 on Google Maps",
      React.createElement("br"),
      "in your ",
      React.createElement("em", null, "3–5 mile trade area."),
    ),
    lead: "We are a specialist Local SEO partner for independent self-storage operators. We move your facility into the map pack for the storage searches renters actually run inside your service radius — without pay-per-lead fees or generic agency tactics.",
    primaryCta: { label: "Get a free local visibility audit", href: "/contact" },
    ghostCta: { label: "See ranking data →", href: "#proof" },
    dashboard: {
      title: "Map pack tracker — Live",
      tracking: "Tracking",
      period: "Trade area",
      metrics: [
        { label: "Map pack appearances", value: "412", delta: "↑ 168% vs prior 90d" },
        { label: "Direction requests", value: "287", delta: "↑ 94% vs prior 90d" },
        { label: "Avg. pack position", value: "2.3", delta: "Was 8.4 at start" },
      ],
      chartLabel: "Map pack impressions — trailing 14 weeks",
      sparkline: [18, 24, 28, 32, 41, 48, 54, 61, 68, 74, 80, 86, 91, 96],
      rankings: [
        { pos: "#1", kw: "storage units near me", change: "↑ +9", clicks: "724", top: true },
        { pos: "#2", kw: "self storage [city]", change: "↑ +6", clicks: "548", top: true },
        { pos: "#3", kw: "climate controlled storage", change: "New", clicks: "341", isNew: true },
        { pos: "#4", kw: "10x10 storage unit [zip]", change: "↑ +4", clicks: "219" },
      ],
    },
  },
  marquee: ["Google Business Profile", "Map Pack Ranking", "Citations", "NAP Consistency", "Review Velocity", "Local Landing Pages", "Service Area Targeting", "ZIP Keyword Coverage", "GBP Photos", "Posts & Offers", "Q&A Management", "Local Schema"],
  problem: {
    pill: "Why you are losing local renters",
    headline: React.createElement(React.Fragment, null,
      "The map pack is winner-take-most.",
      React.createElement("br"),
      "Three failures keep you out of it.",
    ),
    lead: "If your facility is not in the top three Google Maps results inside your trade area, the majority of nearby clicks go to a competitor. These are the exact gaps we close in the first 90 days.",
    cards: [
      { num: "Problem 01", title: "Location drift on Google Maps", desc: "Your pin shows several miles from where the facility actually sits, so renters call the operator closest to where they searched.", tag: "GBP · Map pin · Service area" },
      { num: "Problem 02", title: "Review gap against the facility next door", desc: "Competitors show 4.8 stars and 200+ recent reviews while you sit on a handful from years ago. Renters pick them before they ever click your listing.", tag: "Reviews · Velocity · Response rate" },
      { num: "Problem 03", title: "Wrong hours, missing categories, stale photos", desc: "Renters see incorrect office hours or gate access times and assume you are closed. Missing service categories give Google no reason to surface you.", tag: "Categories · Hours · Photos" },
    ],
    visual: {
      title: "What a missed map pack ranking costs",
      sub: "Typical single facility, monthly",
      rows: [
        { label: "Pay-per-lead aggregator clicks lost", value: "$2,400 / mo", tone: "r", valueClass: "red" },
        { label: "Paid search spend covering the gap", value: "$1,800 / mo", tone: "a", valueClass: "red" },
        { label: "Direction requests sent to competitors", value: "~210 / mo", tone: "a", valueClass: "red" },
        { label: "Organic map pack clicks (after programme)", value: "$0 / lead", tone: "g", valueClass: "green" },
      ],
      totalLabel: "Cost per map pack lead at month 6",
      totalValue: "$0.00",
    },
    inlineCta: {
      strong: "See exactly where your pin is losing renters",
      body: "Free audit. We map the gap between you and the top three results in your trade area.",
      ctaLabel: "Get free audit →",
      ctaHref: "/contact",
    },
  },
  approach: {
    pill: "Our approach",
    headline: React.createElement(React.Fragment, null,
      "Four moves that put your facility",
      React.createElement("br"),
      "in the top three.",
    ),
    lead: "No generic Local SEO playbook. Every step is built for the way renters search for self-storage and the way Google ranks storage facilities specifically.",
    steps: [
      { phase: "Step 01", title: "Google Business Profile mastery", desc: "Weekly profile management. Correct primary category, properly configured attributes, fresh photos of every unit type, posts and offers kept current, and the structured signals that tell Google your facility is the most relevant result in its radius.", tags: ["GBP", "Categories", "Photos", "Posts"] },
      { phase: "Step 02", title: "Near-me keyword optimisation", desc: 'Local landing pages built for the phrases renters actually use — "climate-controlled storage in {City}", "vehicle and RV storage near {Neighborhood}", "cheapest 10x10 units near me", "drive-up storage units in {ZIP}".', tags: ["Location pages", "Unit-size pages", "ZIP targeting"] },
      { phase: "Step 03", title: "Hyper-local citation building", desc: "Your facility added to 50+ local directories and self-storage-specific databases with consistent NAP data. This is the topical authority that lifts map rankings above generic competitors.", tags: ["NAP", "Citations", "Directories"] },
      { phase: "Step 04", title: "Review velocity and response", desc: "An automated review request flow tied to your booking software, plus templated or fully managed responses. Steady review volume and a high response rate are direct map pack ranking signals.", tags: ["Review automation", "Response", "Velocity"] },
    ],
    ctaText: React.createElement(React.Fragment, null,
      React.createElement("strong", null, "Want to see what each step finds for your facility?"),
      " The audit is free and arrives in writing within five business days.",
    ),
    ctaLabel: "Start with a free audit →",
    ctaHref: "/contact",
  },
  proof: {
    pill: "Verified results",
    headline: "Map pack data from active client accounts.",
    dataCard: {
      title: "Single facility, FL — Months 1–9",
      source: "GBP Insights",
      kpis: [
        { label: "Map clicks", value: "12.6K", delta: "↑ 214% vs baseline" },
        { label: "Avg. pack pos.", value: "2.3", delta: "Was 8.4 at start" },
        { label: "Direction reqs.", value: "2.4K", delta: "↑ 167% vs baseline" },
      ],
      positionLabel: "Google Maps position — primary keywords",
      positions: [
        { kw: "storage units near me", w: "97%", num: "#1", top: true },
        { kw: "self storage [city]", w: "92%", num: "#2", top: true },
        { kw: "climate controlled storage", w: "85%", num: "#3" },
        { kw: "10x10 storage unit [zip]", w: "74%", num: "#4" },
        { kw: "RV storage near [zip]", w: "60%", num: "#6" },
      ],
      journeyLabel: "Map pack impressions — month by month",
      bars: [
        { h: 14, cls: "" }, { h: 20, cls: "" }, { h: 26, cls: "" },
        { h: 38, cls: "mid" }, { h: 46, cls: "mid" },
        { h: 58, cls: "high" }, { h: 68, cls: "high" }, { h: 76, cls: "high" },
        { h: 92, cls: "peak" },
      ],
      months: ["M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9"],
    },
    aggCards: [
      { num: "2.3", label: "Avg. map pack position at month 6", note: "Was 8.4 at engagement start" },
      { num: React.createElement(React.Fragment, null, "94", React.createElement("span", null, "%")), label: "Clients ranking in top 3 by month 6", note: "Across all primary keywords" },
      { num: React.createElement(React.Fragment, null, "50", React.createElement("span", null, "+")), label: "Local citations per facility", note: "Storage-specific databases included" },
      { num: "$0", label: "Cost per map pack lead, month 6+", note: "Across all active clients" },
    ],
    testimonial: {
      quote: "Helped Pickfords in the UK rank their independent facilities across 33 states. The map pack work moved the needle within the first quarter — direction requests started landing before we had even finished the citation cleanup.",
      attribution: "Independent storage facility owner",
      location: "Florida",
    },
    auditCta: {
      label: "Your facility could look like this",
      text: "We connect your GBP, GA4, and GSC in the first week. You see your own ranking and conversion data in the same dashboard format above.",
      features: [
        "Map pack gap analysis in week one",
        "Trade-area competitor ranking baseline",
        "Citation and NAP consistency audit",
        "No sales call required to receive the audit",
      ],
      ctaLabel: "Request your free audit →",
      ctaHref: "/contact",
    },
  },
  faq: {
    pill: "Common questions",
    headline: "Before you hire a Local SEO partner.",
    lead: "If your question is not here, reach out directly. We answer before you commit to anything.",
    asideStrong: "Still weighing it up? Talk to us first.",
    asideBody: "We will review your current map pack rankings, point out the biggest gap, and tell you honestly whether Local SEO is the right move for your facility right now.",
    asideCtaLabel: "Request a free conversation →",
    asideCtaHref: "/contact",
    items: [
      { q: "How long until I rank in the top three of Google Maps?", a: "Most self-storage clients see meaningful map ranking improvement within 45 to 90 days. The exact timeline depends on your starting position, review count, and how competitive your trade area is. We share a baseline ranking report in week one so you can measure movement against it.", open: true },
      { q: "Do you handle review responses for us?", a: "Yes — either we provide response templates your on-site team uses, or we actively manage every response on your behalf. Either way the review profile stays active, which Google treats as a positive ranking signal." },
      { q: "Does this work for multi-location operators?", a: "Yes. Multi-location programmes get a localised strategy per facility so your own listings complement each other instead of competing for the same keywords. Pricing scales by facility count." },
      { q: "Do I need a new website for Local SEO to work?", a: "No. Most of the first-90-day wins come from Google Business Profile optimisation, citation cleanup, and local landing pages added to your existing site. A rebuild is only suggested if the audit shows your current platform is blocking ranking — and we say so directly." },
      { q: "How do you measure results?", a: "We connect your GA4 and Google Search Console accounts in week one. Monthly reporting ties map pack position movement to reservation form completions and tracked phone calls, so you see which ranking changes actually produced move-ins." },
    ],
  },
  finalCta: {
    headline: React.createElement(React.Fragment, null,
      "Ready to take the top three",
      React.createElement("br"),
      "of the map in your trade area?",
    ),
    lead: "Request a free local visibility audit. We review your GBP, citations, and current map pack position, then deliver a written report within five business days.",
    primaryLabel: "Claim my local audit",
    primaryHref: "/contact",
    ghostLabel: "See ranking data first",
    reassurance: ["Free, no obligation", "Written report in 5 business days", "No sales call required", "Yours to keep regardless"],
  },
};
