import type { V2ServicePageProps } from "./V2ServicePage";
import React from "react";

export const multiLocationContent: V2ServicePageProps = {
  hero: {
    badge: "Multi-Location SEO · Portfolio reporting",
    title: React.createElement(React.Fragment, null,
      "Scale local SEO across every",
      React.createElement("br"),
      "facility ", React.createElement("em", null, "without cannibalising yourself."),
    ),
    lead: "Whether you run five facilities or fifty, we build a local SEO programme that lifts every location without pitting your own facilities against each other for the same keywords. Portfolio-level reporting included.",
    primaryCta: { label: "Get my free multi-location audit", href: "/contact" },
    ghostCta: { label: "See portfolio data →", href: "#proof" },
    dashboard: {
      title: "Portfolio rollup — 12 facilities",
      tracking: "Tracking",
      period: "Last 30 days",
      metrics: [
        { label: "Facilities in top 3", value: "11 / 12", delta: "Up from 7 / 12" },
        { label: "Portfolio map clicks", value: "38.4K", delta: "↑ 142% YoY" },
        { label: "Avg. pack pos.", value: "2.1", delta: "Was 6.8 at start" },
      ],
      chartLabel: "Portfolio impressions — trailing 14 weeks",
      sparkline: [28, 32, 36, 42, 48, 54, 62, 68, 74, 80, 85, 90, 94, 98],
      rankingsHeader: { pos: "Pos.", kw: "Facility — keyword", change: "Change", clicks: "Clicks" },
      rankings: [
        { pos: "#1", kw: "Dallas-Plano · self storage", change: "↑ +5", clicks: "2.1K", top: true },
        { pos: "#1", kw: "Austin-South · climate storage", change: "↑ +3", clicks: "1.6K", top: true },
        { pos: "#2", kw: "Houston-Heights · 10x10 units", change: "New", clicks: "1.2K", isNew: true },
        { pos: "#3", kw: "SA-Stone Oak · drive-up storage", change: "↑ +2", clicks: "984" },
      ],
    },
  },
  marquee: ["Portfolio rollup reporting", "Trade-area mapping", "Overlap-zone resolution", "Template-based location pages", "Centralised GBP management", "Review velocity per facility", "Kiosk-facility configuration", "BI feed integration", "Facility-level dashboards", "No internal cannibalisation", "Quarterly portfolio reviews", "Multi-state coverage"],
  problem: {
    pill: "Why scaling local SEO breaks",
    headline: React.createElement(React.Fragment, null,
      "Without a system, your own",
      React.createElement("br"),
      "facilities compete with each other.",
    ),
    lead: "Multi-location operators face a different challenge than single-facility owners. When your facilities sit close to each other, poor SEO architecture causes them to compete for the same searches. These are the issues we find on almost every portfolio audit.",
    cards: [
      { num: "Problem 01", title: "Near-duplicate location pages", desc: "Each facility has a page built from the same template with the city name swapped in. Google sees thin duplicates and ranks none of them properly, or rotates which one shows for the same keyword.", tag: "Duplicate content · Template pages" },
      { num: "Problem 02", title: "Inconsistent NAP across listings", desc: "Different phone numbers, address abbreviations, or naming conventions across Google, Apple Maps, Yelp, and directories. Each inconsistency weakens map rankings at every location.", tag: "NAP · Citations · Cross-platform" },
      { num: "Problem 03", title: "No portfolio-level visibility", desc: "Reviews concentrated at one or two flagship facilities while others sit on fewer than ten. No shared dashboard, so operations leaders cannot see which locations are winning and which are stuck.", tag: "Reporting · Review distribution" },
    ],
    visual: {
      title: "What unmanaged portfolio SEO costs",
      sub: "Typical 10-facility operator",
      rows: [
        { label: "Facilities ranking below top 5", value: "6 of 10", tone: "r", valueClass: "red" },
        { label: "Overlap zones with own-brand cannibalisation", value: "4 zones", tone: "a", valueClass: "red" },
        { label: "Facilities with stale GBP (90+ days)", value: "7 of 10", tone: "a", valueClass: "red" },
        { label: "After programme: all top-3 in primary trade area", value: "10 / 10", tone: "g", valueClass: "green" },
      ],
      totalLabel: "Avg. portfolio pack position at month 6",
      totalValue: "2.1",
    },
    inlineCta: {
      strong: "See where your portfolio is leaking move-ins",
      body: "Free audit. We map every facility, every overlap zone, and every NAP inconsistency dragging the portfolio down.",
      ctaLabel: "Get free audit →",
      ctaHref: "/contact",
    },
  },
  approach: {
    pill: "Our framework",
    headline: React.createElement(React.Fragment, null,
      "One system. Every facility lifted.",
      React.createElement("br"),
      "No internal competition.",
    ),
    lead: "Multi-location self-storage SEO has specifics that single-facility SEO and multi-location retail SEO both miss. Here is how we run it.",
    steps: [
      { phase: "Step 01", title: "Trade-area mapping", desc: "We map every facility's actual trade area and identify overlap zones where two of your facilities compete for the same renters. For each overlap, we decide which facility wins which keyword and build the local pages and GBP settings accordingly.", tags: ["Trade areas", "Overlap zones", "Keyword assignment"] },
      { phase: "Step 02", title: "Location page architecture at scale", desc: "Template-based location page system where each page has unique, substantive content about that specific facility, its trade area, and its unit mix. No thin duplicates. No near-identical paragraphs with the city name swapped in.", tags: ["Page architecture", "Unique copy", "Schema per location"] },
      { phase: "Step 03", title: "Centralised GBP + review velocity", desc: "Every listing managed through a centralised workflow — consistent categories, attributes, hours, photos, and posts across every facility, with location-specific details where they matter. Each facility gets a weekly review-request flow tied to your booking software.", tags: ["GBP at scale", "Review automation", "Kiosk-friendly"] },
      { phase: "Step 04", title: "Portfolio-level reporting", desc: "One dashboard covering every facility — map rankings, direction requests, phone calls, website visits, and reservations attributed to search. Roll-up views for ownership. Facility-level views for operations. BI-feed integration if you have a stack.", tags: ["Roll-up", "Facility-level", "BI integration"] },
    ],
    ctaText: React.createElement(React.Fragment, null,
      React.createElement("strong", null, "Want the portfolio audit on your locations?"),
      " We map every facility's visibility, every overlap, every gap.",
    ),
    ctaLabel: "Start with a free audit →",
    ctaHref: "/contact",
  },
  proof: {
    pill: "Verified results",
    headline: "Portfolio data from active multi-location accounts.",
    dataCard: {
      title: "12-facility operator, Southeast — Months 1–9",
      source: "Portfolio rollup",
      kpis: [
        { label: "Facilities in top 3", value: "11 / 12", delta: "Up from 7 / 12" },
        { label: "Portfolio clicks", value: "38.4K", delta: "↑ 142% vs prior 90d" },
        { label: "Overlap zones resolved", value: "4 / 4", delta: "No cannibalisation" },
      ],
      positionLabel: "Map pack position — by facility",
      positions: [
        { kw: "Facility 01 (flagship, TX)", w: "97%", num: "#1", top: true },
        { kw: "Facility 04 (suburban, GA)", w: "92%", num: "#2", top: true },
        { kw: "Facility 07 (kiosk, FL)", w: "85%", num: "#2", top: true },
        { kw: "Facility 09 (climate, NC)", w: "78%", num: "#3" },
        { kw: "Facility 12 (new build, SC)", w: "55%", num: "#5" },
      ],
      journeyLabel: "Portfolio direction requests — month by month",
      bars: [
        { h: 22, cls: "" }, { h: 28, cls: "" }, { h: 34, cls: "" },
        { h: 42, cls: "mid" }, { h: 52, cls: "mid" },
        { h: 64, cls: "high" }, { h: 74, cls: "high" }, { h: 84, cls: "high" },
        { h: 96, cls: "peak" },
      ],
      months: ["M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9"],
    },
    aggCards: [
      { num: React.createElement(React.Fragment, null, "11", React.createElement("span", null, "/12")), label: "Facilities in top 3 at month 6", note: "Across primary keyword set" },
      { num: "2.1", label: "Avg. portfolio map pack position", note: "Was 6.8 at engagement start" },
      { num: "0", label: "Overlap-zone keyword conflicts", note: "Down from 4 at start" },
      { num: React.createElement(React.Fragment, null, "94", React.createElement("span", null, "%")), label: "Client renewal at year two", note: "Multi-location accounts" },
    ],
    testimonial: {
      quote: "We run twelve facilities across three states. Before working with SelfStorage.help, three of our locations were stuck in the map pack. Within six months, every facility ranked in the top three for its core keyword set — and we finally had one dashboard to see all of it.",
      attribution: "Regional director — Multi-location operator",
      location: "Southeast US",
    },
    auditCta: {
      label: "Run the portfolio audit on your locations",
      text: "We map every facility's current visibility, flag the overlap zones and NAP inconsistencies, and show you the quickest path to lifting occupancy across the portfolio.",
      features: [
        "Per-facility ranking baseline",
        "Overlap-zone analysis",
        "NAP consistency audit across all listings",
        "Portfolio-level reporting sample included",
      ],
      ctaLabel: "Request your free audit →",
      ctaHref: "/contact",
    },
  },
  faq: {
    pill: "Common questions",
    headline: "Things operators usually ask.",
    lead: "If your question is not here, reach out directly. We answer before you commit to anything.",
    asideStrong: "Not sure if the portfolio programme fits?",
    asideBody: "If you run two to four facilities, the standard Local SEO programme with custom reporting is usually a better fit. We will tell you honestly which one is right after the audit.",
    asideCtaLabel: "Request a free conversation →",
    asideCtaHref: "/contact",
    items: [
      { q: "How many facilities do I need to qualify?", a: "The portfolio programme is built for operators with five or more facilities. Owners with two to four facilities are better served by our standard Local SEO programme with custom reporting layered on.", open: true },
      { q: "Do you work with kiosk-based facilities?", a: "Yes. Kiosk facilities need specific Google Business Profile configuration and review programme adjustments, which we handle. NAP consistency and verification health are especially important on kiosk locations." },
      { q: "Can you coordinate with my in-house marketing team?", a: "Yes. We often work alongside in-house teams, taking the local SEO and content production work while your team handles brand, paid media, or other marketing functions. We integrate with your tools and reporting cadence." },
      { q: "What reporting do I get?", a: "Monthly portfolio-level rollups plus a live dashboard with facility-level data refreshed weekly. If you have a BI stack (Looker, Tableau, Snowflake), we can feed data directly into it instead of using our dashboard." },
      { q: "How do you handle overlap zones between my own facilities?", a: "We map every trade area, identify the zones where two of your facilities compete for the same renters, and assign each keyword/area to the facility that should win it. The other facility gets routed to its own distinct keyword set so neither one starves." },
      { q: "How long before every facility moves?", a: "Flagship and well-positioned facilities usually move within 45–90 days. Stuck or newly-opened facilities can take 4–6 months depending on review baseline, NAP cleanup needs, and trade-area competition." },
    ],
  },
  finalCta: {
    headline: React.createElement(React.Fragment, null,
      "Ready to scale local SEO across",
      React.createElement("br"),
      "your portfolio? Free audit.",
    ),
    lead: "Get a free multi-location audit. We map every facility's current visibility, flag the gaps, and show you the quickest path to lifting occupancy across the portfolio.",
    primaryLabel: "Get my multi-location audit",
    primaryHref: "/contact",
    ghostLabel: "See portfolio data first",
    reassurance: ["Per-facility baseline", "Overlap-zone analysis", "NAP audit across listings", "Portfolio reporting sample"],
  },
};
