import type { V2ServicePageProps } from "./V2ServicePage";
import React from "react";

export const technicalSeoContent: V2ServicePageProps = {
  hero: {
    badge: "Technical SEO · Site & GBP foundation",
    title: React.createElement(React.Fragment, null,
      "Fix the hidden technical issues",
      React.createElement("br"),
      "that ", React.createElement("em", null, "quietly suppress your rankings."),
    ),
    lead: "Most storage operators have clean copy and a decent Google Business Profile but still cannot break the top three on Google. The reason almost always lives under the surface — broken schema, slow mobile loads, indexation issues, and dozens of other technical problems search engines hold against you.",
    primaryCta: { label: "Get your free technical SEO audit", href: "/contact" },
    ghostCta: { label: "See real recoveries →", href: "#proof" },
    dashboard: {
      title: "Core Web Vitals — Live audit",
      tracking: "Crawling",
      period: "60-point scan",
      metrics: [
        { label: "LCP (mobile)", value: "1.8s", delta: "Was 4.6s at start" },
        { label: "Site health", value: "94%", delta: "↑ from 47% baseline" },
        { label: "Schema coverage", value: "12/12", delta: "All storage types valid" },
      ],
      chartLabel: "PageSpeed score — trailing 14 audits",
      sparkline: [22, 24, 28, 31, 38, 45, 52, 58, 64, 70, 78, 85, 91, 96],
      rankingsHeader: { pos: "Sev.", kw: "Issue", change: "Status", clicks: "Pages" },
      rankings: [
        { pos: "✓", kw: "Schema markup deployed", change: "Fixed", clicks: "48", top: true },
        { pos: "✓", kw: "Render-blocking scripts", change: "Fixed", clicks: "21", top: true },
        { pos: "!", kw: "Mobile tap targets too small", change: "Queued", clicks: "12", isNew: true },
        { pos: "!", kw: "Mixed-content warnings", change: "Fixing", clicks: "7" },
      ],
    },
  },
  marquee: ["Site speed", "Core Web Vitals", "Schema for storage", "Mobile-first audit", "Crawl & indexation fixes", "GBP technical health", "Security & HTTPS", "Local entity wiring", "JavaScript rendering", "Internal linking", "Image SEO", "CTR optimisation"],
  problem: {
    pill: "Why rankings stall",
    headline: React.createElement(React.Fragment, null,
      "Six technical failures keep good",
      React.createElement("br"),
      "storage sites off page one.",
    ),
    lead: "A storage site can look polished and still rank below competitors with weaker content. The reason is almost always technical. These are the issues we find in 90% of independent operator audits.",
    cards: [
      { num: "Problem 01", title: "Slow on mobile, fine on desktop", desc: "Your site loads in 2 seconds on desktop but 7 over mobile LTE. Google ranks the mobile experience first, and most renters search from a phone.", tag: "Core Web Vitals · Mobile speed" },
      { num: "Problem 02", title: "Missing or broken schema markup", desc: "Without LocalBusiness, SelfStorage, and FAQ schema correctly deployed, search engines and AI tools have no structured way to understand what you offer or where you operate.", tag: "Schema · Structured data · AEO" },
      { num: "Problem 03", title: "Indexation and crawl budget waste", desc: "Pages you want ranked are blocked, duplicated, or buried behind redirects. Pages you do not want indexed are eating your crawl budget. Most owners never notice.", tag: "Crawl · Sitemap · Canonicals" },
    ],
    visual: {
      title: "What a broken technical stack costs",
      sub: "Typical single-facility audit findings",
      rows: [
        { label: "Mobile LCP failing Core Web Vitals", value: "4.6s avg", tone: "r", valueClass: "red" },
        { label: "Pages blocked from indexation in error", value: "14 pages", tone: "a", valueClass: "red" },
        { label: "Missing storage-specific schema types", value: "9 of 12", tone: "a", valueClass: "red" },
        { label: "After programme: schema, speed, crawl all green", value: "100%", tone: "g", valueClass: "green" },
      ],
      totalLabel: "Site health score at month 2",
      totalValue: "94 / 100",
    },
    inlineCta: {
      strong: "See exactly what is suppressing your rankings",
      body: "Free 60-point technical audit covers your site and your Google Business Profile.",
      ctaLabel: "Get free audit →",
      ctaHref: "/contact",
    },
  },
  approach: {
    pill: "Our technical SEO process",
    headline: React.createElement(React.Fragment, null,
      "Audit, fix, validate, monitor —",
      React.createElement("br"),
      "in that order, every time.",
    ),
    lead: "A real technical SEO engagement is not a one-time audit. It is a structured programme that uncovers issues, fixes them at the root, validates the fixes worked, and monitors for regressions.",
    steps: [
      { phase: "Week 01", title: "Full technical audit", desc: "We crawl your site the way Google does, run a complete GBP technical health check, test Core Web Vitals across multiple devices and networks, and document every issue in a prioritised action list with severity ratings.", tags: ["Crawl", "GBP audit", "CWV"] },
      { phase: "Week 02", title: "Foundation fixes deployed", desc: "The high-impact fixes ship first. Schema deployment, robots and sitemap corrections, redirect cleanup, render-blocking script removal, and the highest-leverage GBP corrections. Most facilities see initial ranking movement from this phase alone.", tags: ["Schema", "Sitemaps", "Redirects"] },
      { phase: "Week 03–04", title: "Speed, architecture, mobile", desc: "Image optimisation, font loading strategy, CDN configuration, render-path tuning, internal linking rebuild, pagination handling, and mobile usability fixes on real devices. PageSpeed scores move into the green.", tags: ["LCP", "INP", "Mobile UX"] },
      { phase: "Month 02+", title: "Validate and monitor", desc: "We confirm Google has recrawled and indexed everything correctly, validate every schema type is being read, and set up ongoing monitoring for Core Web Vitals, crawl errors, and indexation drift. Issues get caught before they affect rankings.", tags: ["Monitoring", "Regression", "Quarterly audit"] },
    ],
    ctaText: React.createElement(React.Fragment, null,
      React.createElement("strong", null, "Want the 60-point audit on your facility site?"),
      " Free and delivered in writing within five business days.",
    ),
    ctaLabel: "Start with a free audit →",
    ctaHref: "/contact",
  },
  proof: {
    pill: "Verified results",
    headline: "Recovery data from real client engagements.",
    dataCard: {
      title: "Single facility, NC — Post-rebuild recovery",
      source: "GSC · PageSpeed",
      kpis: [
        { label: "Organic traffic", value: "+67%", delta: "Recovered in 90 days" },
        { label: "Mobile LCP", value: "1.8s", delta: "Was 4.6s at start" },
        { label: "Issues fixed", value: "47", delta: "Across site + GBP" },
      ],
      positionLabel: "Technical health by category",
      positions: [
        { kw: "Core Web Vitals", w: "96%", num: "✓", top: true },
        { kw: "Schema coverage", w: "100%", num: "✓", top: true },
        { kw: "Crawl & indexation", w: "92%", num: "✓" },
        { kw: "GBP technical health", w: "88%", num: "✓" },
        { kw: "Security & HTTPS", w: "100%", num: "✓" },
      ],
      journeyLabel: "Organic sessions — month by month",
      bars: [
        { h: 20, cls: "" }, { h: 24, cls: "" }, { h: 30, cls: "" },
        { h: 40, cls: "mid" }, { h: 50, cls: "mid" },
        { h: 62, cls: "high" }, { h: 72, cls: "high" }, { h: 82, cls: "high" },
        { h: 94, cls: "peak" },
      ],
      months: ["M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9"],
    },
    aggCards: [
      { num: "47", label: "Avg. technical issues found per audit", note: "Across 60-point checklist" },
      { num: React.createElement(React.Fragment, null, "94", React.createElement("span", null, "%")), label: "Sites green on Core Web Vitals", note: "By end of month two" },
      { num: React.createElement(React.Fragment, null, "+58", React.createElement("span", null, " pts")), label: "Avg. PageSpeed score improvement", note: "Mobile, real-world conditions" },
      { num: "30d", label: "Most fixes shipped within", note: "Foundation work in weeks 1–4" },
    ],
    testimonial: {
      quote: "Our Webflow rebuild looked great but our rankings collapsed. Three other agencies told us the site was fine and we just needed more content. SelfStorage.help found 47 technical issues in the first week and most of our rankings came back within 60 days of the fixes shipping.",
      attribution: "Marcus Chen — Single-Facility Operator",
      location: "North Carolina",
    },
    auditCta: {
      label: "Run the audit on your site",
      text: "We deliver a written 60-point audit covering your site and your Google Business Profile. Yours to keep regardless of whether you engage us afterwards.",
      features: [
        "60-point technical checklist",
        "Core Web Vitals on real mobile devices",
        "GBP technical health included",
        "No sales call required to receive the audit",
      ],
      ctaLabel: "Request your free audit →",
      ctaHref: "/contact",
    },
  },
  faq: {
    pill: "Common questions",
    headline: "Things owners usually ask.",
    lead: "If your question is not here, reach out directly. We answer before you commit to anything.",
    asideStrong: "Not sure if it is a technical issue?",
    asideBody: "We will tell you honestly during the audit whether technical work is what will move your rankings, or whether content or links would be the bigger lever for your specific facility.",
    asideCtaLabel: "Request a free conversation →",
    asideCtaHref: "/contact",
    items: [
      { q: "How is this different from a one-time technical audit?", a: "A one-time audit gives you a list. Our service delivers the fixes, validates they worked, and monitors for regressions. Technical issues do not stay fixed on their own — platform updates, new plugins, content changes, and algorithm shifts all introduce new issues.", open: true },
      { q: "Do you work with my specific platform?", a: "Yes. We have deep experience with WordPress, Webflow, Squarespace, Shopify, Wix, and custom-built sites. Each platform has its own technical quirks and ranking pitfalls. We adjust the approach based on what you actually run on." },
      { q: "What if my site needs a rebuild rather than fixes?", a: "We will tell you directly during the audit. Some technical issues are platform-level limitations rather than fixable bugs. If a rebuild is the better path, we explain why and can recommend the right platform. We do not push rebuilds when fixes will do." },
      { q: "Can you fix issues from a previous agency or developer?", a: "Yes. A significant portion of our audits uncover damage from prior work — broken redirects, bad schema, plugin conflicts, abandoned tracking codes. Cleanup is part of the engagement, not a separate add-on." },
      { q: "Will this help with AI search like ChatGPT and Perplexity?", a: "Yes, and significantly. AEO and GEO visibility depends almost entirely on technical signals — schema depth, entity wiring, citation consistency, and structured data quality. Our work directly improves how AI engines understand and surface your facility." },
      { q: "How quickly will I see results?", a: "Most operators see initial movement within 30 days from the foundation fixes alone. Significant ranking and traffic recovery typically settles in by month two or three. Sites coming back from a major issue can take longer depending on the depth of the damage." },
    ],
  },
  finalCta: {
    headline: React.createElement(React.Fragment, null,
      "Find out exactly what is holding",
      React.createElement("br"),
      "your facility back. Free audit.",
    ),
    lead: "Drop your facility website and we will send a 60-point technical audit covering your site, your Google Business Profile, and the specific fixes that will move your rankings fastest.",
    primaryLabel: "Send my technical audit",
    primaryHref: "/contact",
    ghostLabel: "See recovery data first",
    reassurance: ["60-point checklist", "Site + GBP both covered", "Most fixes shipped in 30 days", "Yours to keep regardless"],
  },
};
