// Every city slug supported by the live city page (app/storage-search/[city]),
// mapped to its two-letter state code. Shared with the search components so
// they can resolve a typed city name to a real page instead of a dead search.
export const CITY_STATES: Record<string, string> = {
  "american-fork": "UT", "apple-valley": "UT", bluffdale: "UT", bountiful: "UT", "brigham-city": "UT", "cedar-city": "UT", centerville: "UT", clearfield: "UT", clinton: "UT", draper: "UT", farmington: "UT", "garden-city": "UT", grantsville: "UT", "heber-city": "UT", herriman: "UT", highland: "UT", hooper: "UT", hurricane: "UT", kearns: "UT", layton: "UT", lehi: "UT", lindon: "UT", logan: "UT", magna: "UT", midvale: "UT", millcreek: "UT", "mountain-green": "UT", murray: "UT", "north-logan": "UT", "north-ogden": "UT", "north-salt-lake": "UT", ogden: "UT", orem: "UT", "park-city": "UT", parowan: "UT", payson: "UT", "pleasant-grove": "UT", providence: "UT", provo: "UT", richmond: "UT", riverdale: "UT", riverton: "UT", roosevelt: "UT", "salt-lake-city": "UT", sandy: "UT", "saratoga-springs": "UT", "south-jordan": "UT", "south-salt-lake": "UT", "spanish-fork": "UT", springville: "UT", "st-george": "UT", sunset: "UT", "syracuse-ut": "UT", taylorsville: "UT", tooele: "UT", washington: "UT", "west-bountiful": "UT", "west-jordan": "UT", "west-point": "UT", "west-valley-city": "UT", "woods-cross": "UT",
  anaheim: "CA", bakersfield: "CA", "cathedral-city": "CA", "chula-vista": "CA", "culver-city": "CA", "daly-city": "CA", "elk-grove": "CA", fontana: "CA", fremont: "CA", fresno: "CA", "garden-grove": "CA", glendale: "CA", "harbor-city": "CA", "huntington-beach": "CA", irvine: "CA", "king-city": "CA", "long-beach": "CA", "los-angeles": "CA", modesto: "CA", "moreno-valley": "CA", "national-city": "CA", oakland: "CA", oceanside: "CA", ontario: "CA", oxnard: "CA", "rancho-cucamonga": "CA", "redwood-city": "CA", riverside: "CA", sacramento: "CA", "san-bernardino": "CA", "san-diego": "CA", "san-francisco": "CA", "san-jose": "CA", "sand-city": "CA", "santa-ana": "CA", "santa-clarita": "CA", "santa-rosa": "CA", stockton: "CA", "sun-city": "CA", "yuba-city": "CA",
  "boca-raton": "FL", brandon: "FL", "cape-coral": "FL", clearwater: "FL", "cooper-city": "FL", "coral-springs": "FL", "dade-city": "FL", davie: "FL", "florida-city": "FL", "fort-lauderdale": "FL", gainesville: "FL", "haines-city": "FL", hialeah: "FL", hollywood: "FL", jacksonville: "FL", "lake-city": "FL", "lake-worth": "FL", lakeland: "FL", miami: "FL", "miami-gardens": "FL", miramar: "FL", "orange-city": "FL", orlando: "FL", "palm-bay": "FL", "palm-city": "FL", "palm-coast": "FL", "pembroke-pines": "FL", "plant-city": "FL", plantation: "FL", "polk-city": "FL", "pompano-beach": "FL", "port-st-lucie": "FL", riverview: "FL", "saint-cloud": "FL", "spring-hill": "FL", "st-petersburg": "FL", tallahassee: "FL", tampa: "FL", "west-palm-beach": "FL",
  andover: "KS", "baldwin-city": "KS", "bonner-springs": "KS", "de-soto": "KS", derby: "KS", "dodge-city": "KS", "el-dorado": "KS", eudora: "KS", gardner: "KS", haysville: "KS", hutchinson: "KS", "junction-city": "KS", "kansas-city-ks": "KS", lansing: "KS", lawrence: "KS", leavenworth: "KS", lenexa: "KS", maize: "KS", "manhattan-ks": "KS", merriam: "KS", mission: "KS", newton: "KS", olathe: "KS", "overland-park": "KS", "park-city-ks": "KS", salina: "KS", shawnee: "KS", "spring-hill-ks": "KS", topeka: "KS", "valley-center": "KS", wichita: "KS", winfield: "KS",
  affton: "MO", arnold: "MO", ballwin: "MO", belton: "MO", "blue-springs": "MO", chesterfield: "MO", "creve-coeur": "MO", "crystal-city": "MO", fenton: "MO", florissant: "MO", gladstone: "MO", grandview: "MO", hazelwood: "MO", independence: "MO", "jefferson-city": "MO", "kansas-city": "MO", "kimberling-city": "MO", kirkwood: "MO", "lake-st-louis": "MO", "lees-summit": "MO", liberty: "MO", "maryland-heights": "MO", mehlville: "MO", oakville: "MO", ofallon: "MO", "platte-city": "MO", raymore: "MO", raytown: "MO", springfield: "MO", "st-charles": "MO", "st-louis": "MO", "st-peters": "MO", "university-city": "MO", "webb-city": "MO", "webster-groves": "MO", wentzville: "MO", "wright-city": "MO",
  albany: "NY", bronx: "NY", brooklyn: "NY", buffalo: "NY", "clifton-park": "NY", "co-op-city": "NY", commack: "NY", coram: "NY", hempstead: "NY", henrietta: "NY", hicksville: "NY", "huntington-station": "NY", "lefrak-city": "NY", "long-island-city": "NY", manhattan: "NY", "mount-vernon": "NY", "new-rochelle": "NY", "new-york-city": "NY", "niagara-falls": "NY", penfield: "NY", queens: "NY", rochester: "NY", schenectady: "NY", "spring-valley": "NY", "starrett-city": "NY", "staten-island": "NY", syracuse: "NY", troy: "NY", "valley-stream": "NY", "west-babylon": "NY", "west-seneca": "NY", "white-plains": "NY", yonkers: "NY",
  bartlesville: "OK", bethany: "OK", bixby: "OK", "broken-arrow": "OK", chickasha: "OK", choctaw: "OK", claremore: "OK", coweta: "OK", "del-city": "OK", edmond: "OK", "el-reno": "OK", glenpool: "OK", guthrie: "OK", jenks: "OK", lawton: "OK", "midwest-city": "OK", moore: "OK", mustang: "OK", newcastle: "OK", norman: "OK", "oklahoma-city": "OK", owasso: "OK", "ponca-city": "OK", "sand-springs": "OK", sapulpa: "OK", "shawnee-ok": "OK", stillwater: "OK", tulsa: "OK", "warr-acres": "OK", yukon: "OK",
  aberdeen: "SD", "belle-fourche": "SD", "box-elder": "SD", "brandon-sd": "SD", brookings: "SD", canton: "SD", custer: "SD", deadwood: "SD", "dell-rapids": "SD", harrisburg: "SD", "hot-springs": "SD", huron: "SD", lead: "SD", madison: "SD", milbank: "SD", mitchell: "SD", "north-sioux-city": "SD", pierre: "SD", "rapid-city": "SD", redfield: "SD", "sioux-falls": "SD", sisseton: "SD", spearfish: "SD", sturgis: "SD", tea: "SD", vermillion: "SD", volga: "SD", watertown: "SD", winner: "SD", yankton: "SD",
  amarillo: "TX", arlington: "TX", austin: "TX", "bay-city": "TX", brownsville: "TX", carrollton: "TX", "corpus-christi": "TX", cypress: "TX", dallas: "TX", denton: "TX", "el-paso": "TX", "fort-worth": "TX", frisco: "TX", garland: "TX", "grand-prairie": "TX", "haltom-city": "TX", "horizon-city": "TX", houston: "TX", irving: "TX", killeen: "TX", laredo: "TX", "lakeside-city": "TX", "league-city": "TX", lewisville: "TX", lubbock: "TX", mcallen: "TX", mckinney: "TX", mesquite: "TX", midland: "TX", "missouri-city": "TX", pasadena: "TX", pearland: "TX", plano: "TX", "round-rock": "TX", "royse-city": "TX", "san-antonio": "TX", "texas-city": "TX", "universal-city": "TX", waco: "TX",
  "atlantic-city": "NJ", "gloucester-city": "NJ", "jersey-city": "NJ", "neptune-city": "NJ", "ocean-city": "NJ", "union-city": "NJ",
};

// The slug-derived title case doesn't always match how a city is actually
// named in the sheet (NYC boroughs in particular are filed under plain
// "New York" rather than "New York City" or "Manhattan"). This overrides
// the city name used to query the data, independent of the URL slug.
export const CITY_NAME_OVERRIDES: Record<string, string> = {
  manhattan: "New York",
  "new-york-city": "New York",
};
